//
// Created by he ke on 17/9/1.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>


/* Header for class com_example_heke_test_MainActivity */

#ifndef LOG_TAG

#define LOG_TAG"ANDROID_LAB"

#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#endif

#ifndef _Included_com_example_heke_test_MainActivity
#define _Included_com_example_heke_test_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_heke_test_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_heke_test_MainActivity_getStringFromNative
        (JNIEnv *env, jobject jobj){

    LOGD("log string from ndk.");

return (*env)->NewStringUTF(env,"HelloFrom JNI78!");

}

#ifdef __cplusplus
}
#endif
#endif

